### ISSUE TITLE
Clean Input by Stripping Puncutation, Handling Extended Characters?

### ISSUE THREAD

**Issue by c-forster** [ropensci/gender#33]
Does it make sense to try to strip punctuation from input strings? Or, perhaps, handle non-ascii characters somehow? 

I was using the package to process names from the recently released [HathiTrust Literary Genres Date](https://sharc.hathitrust.org/genre) and came into the following cases:

```R
library(gender)

> gender('beatrice')
$name
[1] "beatrice"
$proportion_male
[1] 0.0034
$proportion_female
[1] 0.9966
$gender
[1] "female"
$year_min
[1] 1932
$year_max
[1] 2012

> gender('beatrice.')
$name
[1] "beatrice."
$proportion_male
[1] NA
$proportion_female
[1] NA
$gender
[1] NA
$year_min
[1] 1932
$year_max
[1] 2012
```

While a user passing that data almost certainly wants the correct and available answer, the terminal period breaks it. Likewise, consider this case:

```R
> gender('francois')
$name
[1] "francois"
$proportion_male
[1] 0.9963
$proportion_female
[1] 0.0037
$gender
[1] "male"
$year_min
[1] 1932
$year_max
[1] 2012

> gender('françois')
$name
[1] "fran\347ois"
$proportion_male
[1] NA
$proportion_female
[1] NA
$gender
[1] NA
$year_min
[1] 1932
$year_max
[1] 2012
 ```
Here too the desired answer does seem to be in the data, but some aspect of the input prevents the package from returning the (I assume) desired answer. There may be other cases. 

Arguably, this is a matter of sanitizing input should be left to the user (the package only accepts first names, for instance, and leaves it to a user to parse a first name from some source). Yet this also seems relatively easy and might decrease the number of NAs that are returned.

I'll be writing up something to clean the input for my use case; if it makes sense for the package I can fork and issue a pull req.

**Comment by lmullen** [comment]
Thanks for the suggestion, @c-forster. However, this is not a road that I am going to go down. The `gender()` function does work regardless of capitalization, which is a special case that I have to support since the underlying datasets use only lowercase names, but names are typically capitalized. However, punctuation in odd places, initials, first names and surnames together ... there are just too many possible options to support. Removing accents from characters is also very difficult. Base R has the `chartr()` function that lets you replace characters, but doing this consistently for arbitrary languages and encodings is a package in itself. Furthermore, each cleaning operation would come with a performance hit, regardless of whether the cleaning is needed. 

By the way, I see from the output that you are using gender v0.4.x. There is a new release coming in the next couple days that brings support for European/Canadian datasets and significant performance improvements. But now `gender()` will always return a dataframe instead of a list. Hopefully this will be on CRAN soon, but if you're in a hurry you can get a mostly working dev version: `install.packages("gender", repos = "http://packages.ropensci.org")`.

**Comment by c-forster** [comment]
Makes sense; and thanks for the heads up re: on the dev version as well.
