### ISSUE TITLE
Somewhat unique names

### ISSUE THREAD

**Issue by soodoku** [ropensci/gender#38]
Dear Lincoln,

As you know, when we don't have too much data on a name, the gender estimates are liable to be a bit variable. I don't know how common the problem is but there may be two things we could do:
1. Allow people to also get data on the underlying number of people with that name
2. Allow opportunity to provide smoothed estimates --- relationship between gender and names changes over time but generally slowly.

**Comment by lmullen** [comment]
@soodoku Both are valuable suggestions. You can already do both.

1. I don't provide the `n` for the number of names because for some methods I have to make corrections to the data, so the `n` is meaningless. However, you can get the datasets for yourself in the [genderdata](https://github.com/ropensci/genderdata) package.
2. Instead of looking for an estimate for a single year, you should look for an estimate for a range of years. See the documentation for the `years` parameter to the `gender` function.
