### ISSUE TITLE
Why depend on 'stats' and 'utils'?

### ISSUE THREAD

**Issue by tdeenes** [ropensci/gender#57]
Is there a reason why **gender** *depend*s on **stats** and **utils** instead of *import*ing them?

**Comment by lmullen** [comment]
For the same reason that there are many oddities in R packages: to make sure the package passes CRAN's checks. Specifically, in this case the main package requires a data package which cannot go on CRAN. But in order to pass the checks, it is necessary that these packages be loaded and not just imported.
