### ISSUE TITLE
  could not find function "gender_df" error

### ISSUE THREAD

**Issue by datatitanic** [ropensci/gender#69]
I was able to run my code for a project in August with no problems but when I run it now, I get this error:
Error in gender_df(ssa_df, name_col = "first_names", year_col = "years",  : 
  could not find function "gender_df"

This code ran fine before but now it doesn't.  Am I installing the wrong genderdata package?

Here is the code
install.packages("remotes") # if necessary
remotes::install_github("lmullen/gender")
remotes::install_github("lmullen/genderdata")
head(gender)

#I used (method = "ssa"): United States from 1930 to 2012. 

ssa_names <- c("Charlie", "Royal", "Morgan", "Skyler",
               "Frankie", "Oakley", "Justice")
ssa_years <- c(rep(c(2009, 2012), 3), 2012)
ssa_df <- tibble(first_names = ssa_names,
                 last_names = LETTERS[1:7],
                 years = ssa_years,
                 min_years = ssa_years - 3,
                 max_years = ssa_years + 3)

ssa_df

#This dataset connects first names to years but there are columns 
#for minimum and maximum years for possible age range since birth dates are not always exact. 
#We pass this to gender_df() function, which assigns the method that we wish to use and the names of the columns that contain the names and the birth years. The result is a tibble of predictions.

results <- gender_df(ssa_df, name_col = "first_names", year_col = "years",
                     method = "ssa")

results

**Comment by lmullen** [comment]
The `gender_df()` function was removed in the most recent version because of incompatibilities in supporting packages, and because bookkeeping code should be the responsibility of end users. 

If you want to use the previous version you can find it here. https://cran.r-project.org/src/contrib/Archive/gender/

Or, you can look at the package vignettes for approaches to using the package.
